# Generated by Django 3.1.1 on 2020-09-29 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=250)),
                ('product_details', models.CharField(max_length=1200)),
                ('category', models.CharField(choices=[('watch', 'watch'), ('mobile', 'mobile'), ('bag', 'bag'), ('jwellery', 'jwellery'), ('mens clothes', 'mens clothes'), ('womens wear', 'womens wear')], default='watch', max_length=100)),
                ('product_image', models.ImageField(upload_to='product_image/')),
                ('currency', models.CharField(choices=[('₹', '₹'), ('$', '$'), ('€', '€')], default='₹', max_length=10)),
                ('price', models.IntegerField()),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.products')),
            ],
        ),
    ]
