# Generated by Django 3.1.1 on 2020-09-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_orders_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='first_name',
            field=models.CharField(default='', max_length=40, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='last_name',
            field=models.CharField(default='', max_length=60, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
