# Generated by Django 3.1.1 on 2020-09-30 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_orders_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user_profile',
        ),
    ]
