# Generated by Django 3.1.1 on 2020-09-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_remove_orders_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdates',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('update_timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
