# Generated by Django 3.1.1 on 2020-10-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_auto_20200930_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdates',
            name='delievered',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='orderupdates',
            name='order_placed',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=False, max_length=20),
        ),
    ]
