# Generated by Django 3.1.1 on 2020-10-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_auto_20201004_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(default='', max_length=30),
        ),
    ]
