# Generated by Django 3.1.1 on 2020-10-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0022_auto_20201004_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('blog_desc', models.CharField(max_length=10000)),
                ('blog_desc_note', models.CharField(max_length=8000)),
                ('blog_img', models.ImageField(upload_to='blog_images/')),
                ('blog_upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
