# Generated by Django 3.1.1 on 2020-10-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0023_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_desc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
