# Generated by Django 3.1.1 on 2020-10-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0024_auto_20201005_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_img',
            field=models.ImageField(default='', upload_to='blog_author_img/'),
            preserve_default=False,
        ),
    ]
