# Generated by Django 3.1.1 on 2020-10-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_auto_20201002_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='postcode/zipcode'),
        ),
    ]
